"""Read FB-controller registers directly from a running A100 PCIe.

On a host with root access and ``/sys/bus/pci/devices/<BDF>/resource0``
readable (kernel exposes it by default; containers need --privileged or
PCI=allow-bringup), this dumps the live values of the same Family-B
addresses cmpunlocker writes to when unlocking memory geometry.

Outputs are printed both human-readable and as a YAML snippet ready to
paste into ``common/constants.yaml``.

Usage:
    sudo python3 -m tools.dump_running_cfg
    sudo python3 -m tools.dump_running_cfg --bdf 0000:01:00.0
"""

import argparse
import os
import struct
import sys
from typing import Optional


# Family-B addresses from common/constants.yaml with documented labels.
FAMILY_A_RANGES = (
    (0x110000, 0x112000, 'Family A: booter DRAM timing / refresh'),
)
FAMILY_B_RANGES = (
    (0x120000, 0x122000, 'Family B: FB-geometry register table'),
)
LMR_CANDIDATES = (0x122120, 0x122128, 0x122200, 0x122204)
CFG1_CANDIDATES = (0x120048, 0x122204)


def find_first_a100_resource0() -> Optional[str]:
    """Locate the first NVIDIA device with readable resource0."""
    base = '/sys/bus/pci/devices'
    if not os.path.isdir(base):
        return None
    for entry in sorted(os.listdir(base)):
        if ':' not in entry:
            continue
        vendor_path = os.path.join(base, entry, 'vendor')
        try:
            with open(vendor_path, encoding='ascii') as f:
                if f.read().strip() != '0x10de':
                    continue
        except (FileNotFoundError, PermissionError):
            continue
        resource0 = os.path.join(base, entry, 'resource0')
        if os.access(resource0, os.R_OK):
            return entry
    return None


def read_u32(path: str, offset: int):
    """Read a 32-bit little-endian register at ``offset`` from ``path``.

    Returns ``(value, ok)``: ``ok=False`` means the read returned EIO
    (BAR0 region not mapped by the kernel for userspace access — the
    device is listed under sysfs but not actually backed). On a
    containerised A100 without PCIe passthrough this is the expected
    outcome for addresses past the mapped region.
    """
    fd = os.open(path, os.O_RDONLY)
    try:
        os.lseek(fd, offset, os.SEEK_SET)
        data = os.read(fd, 4)
        if len(data) != 4:
            return None, False
        return struct.unpack('<I', data)[0], True
    except OSError:
        return None, False
    finally:
        os.close(fd)


def write_yaml(addrs_with_labels, total_mib=None):
    """Render a YAML snippet ready to paste into constants.yaml."""
    cfg1_lines = []
    lmr_lines = []
    other_lines = []
    for addr, val, label in addrs_with_labels:
        target = other_lines
        if addr in CFG1_CANDIDATES:
            target = cfg1_lines
        elif addr in LMR_CANDIDATES:
            target = lmr_lines
        target.append((addr, val, label))

    if total_mib is None or total_mib >= 81920:
        size_label = 'A100-80GB layout'
    else:
        size_label = 'unknown layout'

    print('# generated by tools.dump_running_cfg — paste into common/constants.yaml')
    print(f'# Memory topology detected: {size_label} ({total_mib} MiB total)' if total_mib
          else '# Memory topology unknown (nvidia-smi not available)')
    if cfg1_lines:
        print('#')
        print('host_bar0_writes.fb_geometry.cfg1:')
        print(f'  addr:  0x{cfg1_lines[0][0]:06x}    # most likely ({size_label})')
        print(f'  value: 0x{cfg1_lines[0][1]:08x}')
        print(f'  note:  "Live BAR0 read at +0x{cfg1_lines[0][0]:06x} = 0x{cfg1_lines[0][1]:08x}"')
        if len(cfg1_lines) > 1:
            print('# Other cfg1 candidates observed:')
            for addr, val, label in cfg1_lines[1:]:
                print(f'#   0x{addr:06x} = 0x{val:08x}  ({label})')
    if lmr_lines:
        print('#')
        print('host_bar0_writes.fb_geometry.lmr:')
        print(f'  addr:  0x{lmr_lines[0][0]:06x}    # most likely ({size_label})')
        print(f'  value: 0x{lmr_lines[0][1]:08x}')
        print(f'  note:  "Live BAR0 read at +0x{lmr_lines[0][0]:06x} = 0x{lmr_lines[0][1]:08x}"')
        if len(lmr_lines) > 1:
            print('# Other lmr candidates observed:')
            for addr, val, label in lmr_lines[1:]:
                print(f'#   0x{addr:06x} = 0x{val:08x}  ({label})')
    if other_lines:
        print('#')
        print('# Other Family-B registers (informational):')
        for addr, val, label in other_lines:
            print(f'#   0x{addr:06x} = 0x{val:08x}  ({label})')
    print()


def collect_addresses(family):
    if family == 'a':
        return [a for lo, hi, _ in FAMILY_A_RANGES for a in range(lo, hi, 4)]
    if family == 'b':
        return [a for lo, hi, _ in FAMILY_B_RANGES for a in range(lo, hi, 4)]
    ranges = FAMILY_A_RANGES + FAMILY_B_RANGES
    return [a for lo, hi, _ in ranges for a in range(lo, hi, 4)]


def main(argv=None):
    p = argparse.ArgumentParser(
        prog='dump_running_cfg',
        description='Read FB-controller registers from a running A100',
        epilog=(
            'Note on PCI passthrough: this tool needs /sys/bus/pci/.../resource0\n'
            'with the BAR memory actually mapped into the kernel\'s user-visible\n'
            'address space. Containers that expose the PCI device through sysfs\n'
            'but back it with virtualised / partially-mapped BAR will report\n'
            'EIO on read; that outcome means the host path is missing the device,\n'
            'not that the tool has a bug. See tools/dump_running_cfg.py for hints.'
        ),
    )
    p.add_argument('--bdf', default=None,
                   help='PCI BDF (e.g. 0000:01:00.0); auto-detect if omitted')
    p.add_argument('--family', choices=('a', 'b', 'all'), default='all')
    p.add_argument('--no-yaml', action='store_true',
                   help='skip the YAML output (raw register values only)')
    args = p.parse_args(argv)

    bdf = args.bdf or find_first_a100_resource0()
    if bdf is None:
        sys.stderr.write(
            'no readable NVIDIA resource0 found. As root with '
            '/sys/bus/pci/devices/.../resource0 accessible, retry. In '
            'containers, run with --privileged or bind-mount the host PCI '
            'sysfs subtree.\n')
        return 1

    path = f'/sys/bus/pci/devices/{bdf}/resource0'
    if not os.access(path, os.R_OK):
        sys.stderr.write(f'{path} not readable as the current user. Re-run as root.\n')
        return 1
    sys.stderr.write(f'reading from {path}\n')

    try:
        total_mib = int(os.popen(
            'nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits,'
            f'--id={os.environ.get("CUDA_VISIBLE_DEVICES", "0")}'
            ' 2>/dev/null').read().strip() or '0') or None
    except Exception:
        total_mib = None

    addrs = collect_addresses(args.family)
    print(f'=== live BAR0 dump, GPU={bdf}, family={args.family} '
          f'(nvidia-smi memory.total={total_mib} MiB) ===')
    results = []
    fail_count = 0
    fail_first = None
    fail_last = None
    for addr in addrs:
        val, ok = read_u32(path, addr)
        if not ok:
            fail_count += 1
            if fail_first is None:
                fail_first = addr
            fail_last = addr
            continue
        results.append((addr, val, ''))

    if not results:
        sys.stderr.write(
            f'no registers read successfully out of {len(addrs)} attempts '
            f'(BAR0 region probably not mapped for userspace access).\n')
        if fail_first is not None:
            extra = f"  (one of {fail_count} consecutive failures) " if fail_count > 1 else ""
            sys.stderr.write(
                f'  first failure at offset 0x{fail_first:x}{extra}\n')
        sys.stderr.write(
            '  → see the "/sys PCI passthrough" note below\n')
        return 1

    by_addr = {}
    for lo, hi, label in (FAMILY_A_RANGES + FAMILY_B_RANGES):
        for addr, val, _ in results:
            if lo <= addr < hi:
                by_addr[addr] = val

    print(f'  read ok={len(by_addr)}, read fail={fail_count} '
          f'(out of {len(addrs)})')
    for addr in sorted(by_addr):
        in_cfg1 = addr in CFG1_CANDIDATES
        in_lmr = addr in LMR_CANDIDATES
        marker = ' (CFG1 candidate)' if in_cfg1 else (' (LMR candidate)' if in_lmr else '')
        print(f'  +0x{addr:06x} = 0x{by_addr[addr]:08x}{marker}')

    if fail_count:
        first = fail_first if fail_first is not None else 0
        last = fail_last if fail_last is not None else 0
        sys.stderr.write(
            f'  note: read failed continuously from 0x{first:x} to 0x{last:x} '
            f'— the kernel only maps part of the resource0 file as '
            f'real BAR memory; the unmapped region above the device\'s '
            f'actual BAR size returns EIO.\n')

    if not args.no_yaml:
        print()
        write_yaml([(a, v, '') for a, v in by_addr.items()], total_mib=total_mib)

    return 0


if __name__ == '__main__':
    sys.exit(main())
